#!/bin/bash

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) lock ;;
                *Logout) i3-msg exit;;
                *Reboot) reboot ;;
                *Shutdown) shutdown now
            esac
